[package]
name = "knapsack_utils"
version = "0.1.1"
edition = "2021"
authors = ["Hugh Brown <hughdbrown@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prng = { git = "https://github.com/hughdbrown/prng.git" }
